### ISSUE TITLE
Employee Product

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#11]
1. The Employee product list page shouldn't be empty. Need to change it

![Screenshot (63)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/f146407f-02ee-422f-8c40-7bb2786f963c)

2. Employee Product>Add New Employee Product - The highlighted portion should be in red color. Reduce the size of the words

![Screenshot (64)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/020c1290-2548-416d-84a6-48cd95437fdc)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
1. After adding new employee product, toast message should appear as **Employee Quantity Added Successfully**. It should not display as employee quantity updated successfully.
2. Employee Product>Add New Employee Product - The highlighted portion should be in red color. Reduce the size of the words - Not Fixed

**Comment by M8Balaji** [comment]
1. point Prabhu will fix and 2. Point fixed

**Comment by Gokilavani-m8** [comment]
1. After adding new employee product, toast message should appear as Employee Product Added Successfully. 
2. After editing new employee product, toast message should appear as Employee Product Updated Successfully. 
3. While editing the Employee and Product field are disabled

![Screenshot (129)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/461da239-4d69-4bb9-aef6-db3b0d757505)

4. The highlighted message should appear as **Only Positive Numbers are Allowed**

![Screenshot (130)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/0224a168-f664-4b7d-9447-1216af1bbe9d)

**Comment by M8Balaji** [comment]
1 and 2 point Prabhu will fix and others were fixed

**Comment by Gokilavani-m8** [comment]
1. After adding new employee product, toast message should appear as **Employee Product Added Successfully** not as Employee Quality/Stock Added Successfully.
2. After editing new employee product, toast message should appear as **Employee Product Updated Successfully** not as Employee Quality/Stock Updated Successfully.
3. While editing the Employee and Product field are disabled - Not Fixed

![Screenshot (151)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/0735f6e0-9172-4390-8870-084a6ba616c5)

4. Rename the field name as **Employee Name**

![Screenshot (162)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/735589ee-d198-44ad-a457-5880223dae1b)

**Comment by M8Balaji** [comment]
Point 3 - As per requirement, It has been disabled

**Comment by Gokilavani-m8** [comment]
Bug#2 - Not Fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
